function [pipeline,opt] = niak_demo_pipeline_stability()
% A demo for NIAK_PIPELINE_STABILITY
%
% SYNTAX:
% [PIPELINE,OPT] = NIAK_DEMO_PIPELINE_STABILITY()
%
% _________________________________________________________________________
% INPUTS:
%
% _________________________________________________________________________
% OUTPUTS:
%
% PIPELINE
%   (structure) the pipeline structure generated by NIAK_PIPELINE_STABILITY
%
% OPT 
%   (structure) the option structure for NIAK_PIPELINE_STABILITY
%
% _________________________________________________________________________
% COMMENTS:
%
% This pipeline cannot be executed. The inputs of the pipeline needs to be
% somewhat prepared from preprocessed data. The demo is just to exemplify
% the syntax and test that the pipeline structure generates OK.
%
% _________________________________________________________________________
% Copyright (c) Pierre Bellec, Centre de recherche de l'institut de 
% Gériatrie de Montréal, Département d'informatique et de recherche 
% opérationnelle, Université de Montréal, 2010.
% Maintainer : pbellec@criugm.qc.ca
% See licensing information in the code.
% Keywords : demo, pipeline, stability, clustering, consensus, resampling,
% bootstrap

% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in
% all copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
% THE SOFTWARE.

%%%%%%%%%%%%%%%%%
%% Input files %%
%%%%%%%%%%%%%%%%%

for num_s = 1:3
    files_in.data{num_s} = ['/home/pbellec/database/test_stability/tseries_subject' num2str(num_s) '.mat'];
end
files_in.atoms = ['/home/pbellec/database/test_stability/brain_rois.mnc.gz'];

%%%%%%%%%%%%%%%%%%%%
%% Options : Misc %%
%%%%%%%%%%%%%%%%%%%%

opt.flag_test = true; 
opt.folder_out = ['/home/pbellec/database/test_stability/stability/'];
for num_s = 1:3
    opt.labels{num_s} = ['subject' num2str(num_s)];
end
opt.labels_maps = opt.labels;
opt.label_figure = 'test_stability';

%%%%%%%%%%%%%%%%%%%%
%% Options : PSOM %%
%%%%%%%%%%%%%%%%%%%%
opt.psom.mode = 'batch';
opt.psom.max_queued = 2;
opt.psom.mode_pipeline_manager = 'batch';

%%%%%%%%%%%%%%%%%%%%%%%%%
%% Options : Stability %%
%%%%%%%%%%%%%%%%%%%%%%%%%
opt.name_brick_stability = 'niak_brick_stability_tseries';
opt.stability.clustering.type = 'kmeans';
opt.stability.clustering.opt.flag_mex = false;
opt.stability.clustering.opt.flag_verbose    = 0;
opt.stability.nb_classes     = 8;
opt.stability.nb_samps       = 5;
opt.stability.normalize.type = 'mean_var';

%%%%%%%%%%%%%%%%%%%%%%%
%% Generate pipeline %%
%%%%%%%%%%%%%%%%%%%%%%%
[pipeline,opt] = niak_pipeline_stability(files_in,opt);
